language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.1

matrix:
  fast_finish: true

addons:
  artifacts:
    paths:
      - $(ls powershell*{deb,pkg,AppImage} | tr "\n" ":")
      - pester-tests.xml

install:
  - pushd tools
  - ./install-powershell.sh
  - popd
  # Default 2.0.0 Ruby is buggy
  # Default bundler version is buggy
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm install ruby-2.3.1; rvm use 2.3.1; fi
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0 &&
      npm install -g markdown-spellcheck@0.11.0;
    fi
  - ulimit -n 4096
  - powershell -File tools/travis.ps1 -Bootstrap

script:
  - powershell -File tools/travis.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi
